[package]
name = "payment-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
crossbeam = "0.8"
csv = { version = "1" }
log = "0.4"
rayon = "1"
serde = { version = "1", features = ["derive" ]}
thiserror = "1"

[dev-dependencies]
serde_test = "1"

[profile.release]
lto = 'thin'
